#!/usr/bin/python3

import sys
import time

def factorize(num)
	'''Take the number as input.
	
args: num: input integer.
	Return: Atuple of two factors if the the number is not a prime.
		None if the number is prime.
 	'''

            for i in range(2, int(num**0.5)+1):
                if num % i == 0:
                    return (i, num//i)
                return None
            if __name__ == "__main__":

            '''Reads the input file.
            '''
            if len(sys.args) != 2:
                print("usage: factors <file>")
                exit()

                input_file = sys.args[1]

                try:
                    with open(input_file, 'r') as f:
                        lines = f.readlines()
                except FileNotFoundError:
                    print("file not found")
                    exit()

                    start_time = time.time()

                    '''loop over each line (which should be contain one natural number per line).
                        and call factorize on ecah number.
                        if factorize return a tuple of factors.
                        it print the factorization in the disred form'''
                for line in lines:
                    num = int(line.strip())
                    factors = factorize(num)
                    if factors:
                        print(f"(num)=(factors[0])*(factors[1])")

                    '''if the elapsed time exceeds 5 seconds.
                        the program exit with an error message.
                    '''

                    if time.time() - start_time > 5:
                        print("Time limit exceeded")

